export enum ErrorCode {
  // INFRA / RPC
  INFRA_RPC_TIMEOUT = "INFRA_RPC_TIMEOUT", // 504 GATEWAY_TIMEOUT
  INFRA_GATEWAY_ERROR = "INFRA_GATEWAY_ERROR", // 502 BAD_GATEWAY

  // AUTH
  AUTH_FAILED = "AUTH_FAILED", // 401 UNAUTHORIZED (또는 400 BAD_REQUEST)
  AUTH_USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS", // 409 CONFLICT

  // SPA
  SPA_ALREADY_EXISTS = "SPA_ALREADY_EXISTS", // 409 CONFLICT

  // SERVER
  SERVER_INTERNAL_ERROR = "SERVER_INTERNAL_ERROR", // 500 INTERNAL_SERVER_ERROR

  // DATABASE
  DATABASE_OPERATION_FAILED = "DATABASE_OPERATION_FAILED", // 500 INTERNAL_SERVER_ERROR
}
