export enum ERROR_CODE {
  // INFRA / RPC
  INFRA_RPC_TIMEOUT = "INFRA_RPC_TIMEOUT", // 504 GATEWAY_TIMEOUT
  INFRA_GATEWAY_ERROR = "INFRA_GATEWAY_ERROR", // 502 BAD_GATEWAY

  // AUTH
  AUTH_FAILED = "AUTH_FAILED", // 401 UNAUTHORIZED (또는 400 BAD_REQUEST)
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED", // 401 UNAUTHORIZED (토큰 인증 실패)
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN", // 403 FORBIDDEN
  AUTH_INSUFFICIENT_ROLE = "AUTH_INSUFFICIENT_ROLE", // 403 FORBIDDEN (역할 권한 부족)
  AUTH_USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS", // 409 CONFLICT

  // USER
  USER_NOT_FOUND = "USER_NOT_FOUND", // 404 NOT_FOUND
  DUPLICATE_PHONE = "DUPLICATE_PHONE", // 409 CONFLICT
  DUPLICATE_NICKNAME = "DUPLICATE_NICKNAME", // 409 CONFLICT
  INVALID_IMAGE_FORMAT = "INVALID_IMAGE_FORMAT", // 400 BAD_REQUEST

  // SPA
  SPA_NOT_FOUND = "SPA_NOT_FOUND", // 400 BAD_REQUEST
  ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND", // 404 NOT_FOUND
  DUPLICATE_LOCATION = "DUPLICATE_LOCATION", // 409 CONFLICT

  // SERVER
  SERVER_INTERNAL_ERROR = "SERVER_INTERNAL_ERROR", // 500 INTERNAL_SERVER_ERROR

  // DATABASE
  DATABASE_OPERATION_FAILED = "DATABASE_OPERATION_FAILED", // 500 INTERNAL_SERVER_ERROR
}
